/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controladora.CtrlIHC;
import Modelo.Cafe;
import java.awt.Component;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author junior
 */
public class AlteraCafe extends javax.swing.JDialog {
private CtrlIHC ctrlIHC;
    /**
    /**
     * Creates new form Comprar
     */
    public AlteraCafe(CtrlIHC ctrlIHC, Cafe cafe) {
      
        initComponents();
          this.ctrlIHC = ctrlIHC;
          setModal(true);
          txtCodCafe.setText(Integer.toString(cafe.getCod()));
          txtNomeCafe.setText(cafe.getNome());
           setLocationRelativeTo(null);
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popmenuCliente = new javax.swing.JPopupMenu();
        alterar = new javax.swing.JMenuItem();
        excluir = new javax.swing.JMenuItem();
        popmenuAvaliacao = new javax.swing.JPopupMenu();
        alterar1 = new javax.swing.JMenuItem();
        excluir1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        txtNomeCafe = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCodCafe = new javax.swing.JTextField();
        btnAlterarCafe = new javax.swing.JButton();

        alterar.setText("Alterar");
        popmenuCliente.add(alterar);

        excluir.setText("Excluir");
        popmenuCliente.add(excluir);

        popmenuAvaliacao.setComponentPopupMenu(popmenuAvaliacao);

        alterar1.setText("Alterar");
        popmenuAvaliacao.add(alterar1);

        excluir1.setText("Excluir");
        popmenuAvaliacao.add(excluir1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome");

        jLabel2.setText("cod:");

        txtCodCafe.setEditable(false);
        txtCodCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodCafeActionPerformed(evt);
            }
        });

        btnAlterarCafe.setText("Alterar");
        btnAlterarCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarCafeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNomeCafe, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                        .addComponent(txtCodCafe))
                    .addComponent(btnAlterarCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodCafe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeCafe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(btnAlterarCafe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodCafeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodCafeActionPerformed

    private void btnAlterarCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarCafeActionPerformed
        try {
            int cod =  Integer.parseInt(txtCodCafe.getText());
            String nome = txtNomeCafe.getText();

            Cafe cafe = new Cafe(cod, nome);

           ctrlIHC.getCtrlDominio().alterarCafe(cafe);
            Component cmpnt = null;
            JOptionPane.showMessageDialog(cmpnt, "Cafe alterado com sucesso!");
             setVisible(false);
            ctrlIHC.janelaTipoCafe();
           ctrlIHC.atualizarAval();
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AlteraCafe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AlteraCafe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAlterarCafeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alterar;
    private javax.swing.JMenuItem alterar1;
    private javax.swing.JButton btnAlterarCafe;
    private javax.swing.JMenuItem excluir;
    private javax.swing.JMenuItem excluir1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu popmenuAvaliacao;
    private javax.swing.JPopupMenu popmenuCliente;
    private javax.swing.JTextField txtCodCafe;
    private javax.swing.JTextField txtNomeCafe;
    // End of variables declaration//GEN-END:variables
}
