/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controladora.CtrlIHC;
import Modelo.Avaliacao;
import Modelo.Cliente;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import org.hibernate.HibernateException;

/**
 *
 * @author junior
 */
public class ConsultarAvaliacao extends javax.swing.JDialog {

    private CtrlIHC ctrlIHC;
    private String janProx;

    /**
     * /**
     * Creates new form Comprar
     */
    public ConsultarAvaliacao(CtrlIHC ctrlIHC, String prox) {

        initComponents();
        this.ctrlIHC = ctrlIHC;
        this.setModal(true);
        setLocationRelativeTo(null);
        preenchertbmcli(0, "");
        btnCAval.setVisible(false);
        if (prox.equals("CAval")) {
            btnCAval.setVisible(true);
            btnEAval.setVisible(false);
        }
        if (prox.equals("consultar")) {
            btnCAval.setVisible(false);
            btnEAval.setVisible(true);
        }
    }

    public void preenchertbmcli(int indice, String str) {
        try {
            ctrlIHC.getCtrlDominio().listarAvaliacao(tblConsultaAval, indice, str);
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popmenuCliente = new javax.swing.JPopupMenu();
        alterar = new javax.swing.JMenuItem();
        excluir = new javax.swing.JMenuItem();
        popmenuAvaliacao = new javax.swing.JPopupMenu();
        alterar1 = new javax.swing.JMenuItem();
        excluir1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        ComboAval = new javax.swing.JComboBox<>();
        txtAvalBusca = new javax.swing.JFormattedTextField();
        btnCAval = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblConsultaAval = new javax.swing.JTable();
        btnEAval = new javax.swing.JButton();

        alterar.setText("Alterar");
        popmenuCliente.add(alterar);

        excluir.setText("Excluir");
        popmenuCliente.add(excluir);

        popmenuAvaliacao.setComponentPopupMenu(popmenuAvaliacao);

        alterar1.setText("Alterar");
        popmenuAvaliacao.add(alterar1);

        excluir1.setText("Excluir");
        popmenuAvaliacao.add(excluir1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar Avaliação"));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/img/buscar.png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ComboAval.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ComboAval.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Provador", "Nº Amostra" }));
        ComboAval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboAvalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComboAval, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(txtAvalBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAvalBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboAval, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btnCAval.setText("Selecionar");
        btnCAval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAvalActionPerformed(evt);
            }
        });

        tblConsultaAval.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº Laudo", "Data", "Nº Amostra", "Cliente", "Provador", "Cata", "Tipo Café"
            }
        ));
        tblConsultaAval.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tblConsultaAvalComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(tblConsultaAval);

        btnEAval.setText("Excluir");
        btnEAval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEAvalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(btnCAval)
                .addGap(77, 77, 77)
                .addComponent(btnEAval)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCAval, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEAval, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(83, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(50, Short.MAX_VALUE)))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Consutar Avaliacao");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (ComboAval.getSelectedIndex() == 0) {
            preenchertbmcli(0, "");
        } else if (ComboAval.getSelectedIndex() == 1) {
            preenchertbmcli(1, txtAvalBusca.getText());
        } else if (ComboAval.getSelectedIndex() == 2) {
            preenchertbmcli(2, txtAvalBusca.getText());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCAvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAvalActionPerformed

        Avaliacao avalSelecionado;
        int linha = tblConsultaAval.getSelectedRow();
        if (linha >= 0) {
            avalSelecionado = (Avaliacao) tblConsultaAval.getValueAt(linha, 0);
            ctrlIHC.setAvalSelecionado(avalSelecionado);
            setVisible(false);

            if (janProx == "compra") {
                ctrlIHC.janelaComprar();
            } else if (janProx == "cadastrarCli") {
                ctrlIHC.janelaCadastrarCliente();
            } else if (janProx == "vender") {
                ctrlIHC.janelaVender();
            } else if (janProx == "novaAval") {
                ctrlIHC.janelaNovaAvalicao();
            }

        } else {
            JOptionPane.showMessageDialog(this, "Selecione um cliente");
        }

    }//GEN-LAST:event_btnCAvalActionPerformed

    private void tblConsultaAvalComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tblConsultaAvalComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tblConsultaAvalComponentShown

    private void btnEAvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEAvalActionPerformed
        int confirma = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir AVALIAÇÃO? ");
        if (confirma == 0) {

            int linha = tblConsultaAval.getSelectedRow();

            if (linha >= 0) {
                try {
                    Object obj = (Object) tblConsultaAval.getValueAt(linha, 0);
                    ctrlIHC.getCtrlDominio().excluiraAval(obj);
                    ((DefaultTableModel) tblConsultaAval.getModel()).removeRow(linha);
                    JOptionPane.showMessageDialog(this, "Avaliação Excluida com Sucesso!");
                    ctrlIHC.atualizarAval();
                } catch (HibernateException ex) {
                    JOptionPane.showMessageDialog(this, "Voce não pode Apagar essa Avaliação");
                    Logger.getLogger(ConsultarAvaliacao.class.getName()).log(Level.SEVERE, null, ex);

                } catch (SQLException ex) {
                    Logger.getLogger(ConsultarAvaliacao.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnEAvalActionPerformed

    private void ComboAvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboAvalActionPerformed
        txtAvalBusca.setText(null);
        if (ComboAval.getSelectedIndex() == 0) {

            txtAvalBusca.setFormatterFactory(null);
            
           
        }


    }//GEN-LAST:event_ComboAvalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboAval;
    private javax.swing.JMenuItem alterar;
    private javax.swing.JMenuItem alterar1;
    private javax.swing.JButton btnCAval;
    private javax.swing.JButton btnEAval;
    private javax.swing.JMenuItem excluir;
    private javax.swing.JMenuItem excluir1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu popmenuAvaliacao;
    private javax.swing.JPopupMenu popmenuCliente;
    private javax.swing.JTable tblConsultaAval;
    private javax.swing.JFormattedTextField txtAvalBusca;
    // End of variables declaration//GEN-END:variables
}
